"""changed schema

Revision ID: 8cb56aba091b
Revises: e7cc49d49589
Create Date: 2019-02-19 12:12:13.065887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb56aba091b'
down_revision = 'e7cc49d49589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('blogs_owner_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.drop_column('blogs', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_owner_id_fkey', 'blogs', 'users', ['owner_id'], ['id'])
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###
